# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"eaSimpleWithExtraLog": "00_algorithms.ipynb",
         "eaMuPlusLambdaWithExtraLog": "00_algorithms.ipynb",
         "eaMuCommaLambdaWithExtraLog": "00_algorithms.ipynb",
         "Parameter": "01_parameter.ipynb",
         "OrderedParameter": "01_parameter.ipynb",
         "IntegerParameter": "01_parameter.ipynb",
         "InListNumericParameter": "01_parameter.ipynb",
         "FloatParameter": "01_parameter.ipynb",
         "LogFloatParameter": "01_parameter.ipynb",
         "CategoricalParameter": "01_parameter.ipynb",
         "BooleanParameter": "01_parameter.ipynb",
         "CallableParameter": "01_parameter.ipynb",
         "cxDictUniform": "02_crossover.ipynb",
         "cxDictBlender": "02_crossover.ipynb",
         "cxDictBlenderIfCan": "02_crossover.ipynb",
         "mutDictRand": "03_mutation.ipynb",
         "mutRand": "03_mutation.ipynb",
         "logx": "04_utils.ipynb",
         "Logbook.plot": "04_utils.ipynb",
         "HallOfFame.__repr__": "04_utils.ipynb",
         "ConcurrentMap": "04_utils.ipynb",
         "parameters2json": "04_utils.ipynb",
         "json2parameters": "04_utils.ipynb",
         "Digits": "05_sample_cases.ipynb",
         "DigitsCV": "05_sample_cases.ipynb",
         "qtuneSimple": "06_quick.ipynb",
         "default_stats": "06_quick.ipynb",
         "qtuneIterate": "06_quick.ipynb",
         "ScikitLearner": "07_sklearn.ipynb",
         "ScikitLearnerCV": "07_sklearn.ipynb"}

modules = ["algorithms.py",
           "parameter.py",
           "crossover.py",
           "mutation.py",
           "utils.py",
           "sample_cases.py",
           "quick.py",
           "sklearn.py"]

doc_url = "https://longqi.cf//eptune/"

git_url = "https://github.com/wanglongqi/eptune/tree/master/"

def custom_doc_links(name): return None
